language: java
jdk:
  - openjdk8
env:
  global:
    - secure: "kyXRewzjVJUf5xryiALn+ytoE/0wH4Er0t47PVMLJkoboAAXGzPpomkLZeO+rZG3JmOXYluyllZKSUvDNZee/9JjX/nw/NSc4qGdZEhWs6r0O3sB9w2Z7g6U0EiOErwb6tqm+AxEpQ8QmDC/1Vv5jMs2SQtyEnbd1ihN4qSg+tHzCu3B8/EIfxkGUv+NlIw8wT79qTAykjzW9vSfvLwtQwQLQ3DfjznqH1rnYq1cjm/t3wipi5hOMRn3TuNYbHzzg3BpeTJ1yehjXt/cNfNFaF0MjX6qt0Xlk2S7mu2RFPdvg+Z0euCEtGt+Fh135xz4TVQqR3eJF4G67Y8O3rGP+mpIaz2jyORwVMXPklVnTL00q1tCXWjyOZMbelSOkJtbylS8/7KlXwY3TSL48diMMYUdXA6xNjKzKmRkDJMYFgNP+9m0QIPJUCjk54zT4pvvGftY1glDJYYeR6+gkODGLZ/6Xu016vcvY5t+Id+DXbCEnirWx1Y2iR7E34pVSfEZJgT+FYOhDrf5cw1pSla2UHozfV59jt3Q3cPXgKL4LfpXUGv9cggEB4RF16+UGPMnBYe6fKOBY0Esh6ScmVw+h5HRruAegmEmUbAxe99uhLPuD6fsyfoUONfaT9oG4heF4D+TgVb2TFUMdDsajrwntLrNTfckv2c1lBgreF455oY="
    - # ^^ COVERALLS_REPO_TOKEN
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN -B

cache:
  directories:
    - ~/.m2/repository