language: java
jdk:
  - openjdk8
env:
  global:
    - secure: "aPMiz/oiVBfVCtAqBu0GkXvP1UV0KXLROXXE4WYNvwhB2VPs8xQDyEw/hgFNbJ03G2DH/E661OWT9MecPopLF9tPCg30OCaBDTWjmwoXGNvE9wkcdstJC2yRF8LDbfFT2jAShytWQG2L4HgKaY83YqgMhPzk9h577ArvZp5ocwVOa9QPBvq5PV3W2BPF+h8nxOuW12d5cPnPdzSuR0fzvaHQFUt3Trispg47DMOCAjzuGTdvre59i0VX9h8e4YLFZmMfqxfz96SwZCHCSSiDNwSM3rc3D7YZeG+bQi7iLU1SOzO8wO9C6axYLeObn1few5CeIyWv9uvrnQ86T8ktbVbZjkRvdexvcxq4HIbob79jQbYmBpfvVvCtYeEivyXX6eauoF3jJ9Ym0nUzzihzW2AsM0ALQjAtlkC/Equo5PJ6K8SQCxXhhh3SEVn/LzKlVjyUI3Wl+gsd2snOAXMkhrcOcQXX7fbl9exnJXk/6UnV/KuFVM7BKz39NGxFLPd0MPB+RlhxQZrj8crTIlGscunYsGSlFMH1HZIgDRMIOKBGHxeQb8+p5Fh+1qr7lyUDMHh2wPrhNGvUbZm0jmr8wfUIDBr3xjLFvMuRXt4Y6dkmHyx4U/CZ9KVN5DhYZPGConz4t448wtbbZegSEO6DMljvOKtilD6zZfAHPrrNFVg="
    - # ^^ COVERALLS_REPO_TOKEN
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f app/pom.xml
script: mvn test coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN -B -f app/pom.xml

cache:
  directories:
    - ~/.m2/repository