version: '2'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  athena:
    image: athena
    ports:
      - "8080:8080"
    environment:
      - MONGO=mongodb://{mongod_host}:27017/athena
      - RABBITMQ={rabbitmq_host}
      - GITHUB_URI=https://github.com
      - GITHUB_ORGANIZATION=netshoes
      - GITHUB_TOKEN=my_token