management:
  security.enabled: false
  info:
    git:
      mode: full

security:
  oauth2:
    client:
      client-id: athena
      client-secret: secret

application:
  security:
    resourceId: athena
    token:
      accessTokenValiditySeconds: 300
      refreshTokenValiditySeconds: 18000
    admin:
      username: admin
      password: admin
  github:
    host: "api.github.com"
    token: "my_token"
    organization: "my_organization"
  rabbitmq:
    consumers:
      project-scan-queue-concurrent-consumers: 5
      project-scan-queue-max-concurrent-consumers: 10
      project-dependencies-analyze-queue-concurrent-consumers: 5
      project-dependencies-analyze-queue-max-concurrent-consumers: 5

spring:
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

  rabbitmq:
    host: localhost
    port: 5672
  data:
    mongodb:
      uri: mongodb://localhost:27017/athena

endpoints:
  env.keys-to-sanitize: username,password,secret,key,.​*credentials.*​,token,vcap_services,spring.data.mongodb.uri
